[package]
name = "color-format-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[features]
default = ["runtime_color"]
runtime_color = []

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
